doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:

            common:
                type: xml
                dir: "%kernel.project_dir%/src/Appto/Common/Infrastructure/Persistence/Doctrine/Mapping"
                prefix: Appto\Common\Domain
                is_bundle: false

            shoppingcart:
                type: xml
                dir: "%kernel.root_dir%/../../../../Appto/ShoppingCart/Infrastructure/Persistence/Doctrine/Entity/Mapping"
                prefix: Appto\ShoppingCart\Domain
                is_bundle: false
