version: '3.6'

services:
    nginx:
        container_name: appto-dev-nginx
        image: nginx:1.15-alpine
        restart: unless-stopped
        expose:
            - '80'
        ports:
            - "8030:80"
        networks:
            - appto-dev
        volumes:
            - ../:/app:delegated
            - ../etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    php:
        container_name: appto-dev-php
        image: php-fpm-dev
        build:
            context: ../
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        expose:
            - '9000'
        ports:
            - "9030:9001"
        networks:
            - appto-dev
        volumes:
            - ../:/app:delegated
        env_file:
            - ../.env
        depends_on:
            - mysql

    mysql:
        container_name: appto-dev-mysql
        image: mariadb:10.4
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ../data/mysql-data:/var/lib/mysql

volumes:
    db-data:
        driver: local

networks:
    appto-dev:
        #external: true
        name: appto_dev_net
